[development]
template_dir = "templates/"
address = "0.0.0.0"
proxy_prefix='/'
wsocket_hostname_port="127.0.0.1:9001"
wssocket_hostname_port="127.0.0.1:9001"

[production]
port=9000
template_dir = "templates/"
proxy_prefix="/game/"
wsocket_hostname_port="bjason.org:81"
wssocket_hostname_port="bjason.org:444"
